services:
  db:
    image: postgres:14
    container_name: prum-postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
    container_name: cloud-front-api
    volumes:
      - ./api:/api
    depends_on:
      - db
    ports:
      - "3000:3000"
    tty: true
    command: rails s -b 0.0.0.0

  front:
    build:
      context: ./front
    container_name: cloud-front-front
    volumes:
      - ./front:/front
    ports:
      - "80:80"
    depends_on:
      - api
    command: npm run dev
    tty: true
      
    