# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/net-protocol/all/net-protocol.rbi
#
# net-protocol-0.1.3

module Net
end
class Net::Protocol
end
class Net::ProtocolError < StandardError
end
class Net::ProtoSyntaxError < Net::ProtocolError
end
class Net::ProtoFatalError < Net::ProtocolError
end
class Net::ProtoUnknownError < Net::ProtocolError
end
class Net::ProtoServerError < Net::ProtocolError
end
class Net::ProtoAuthError < Net::ProtocolError
end
class Net::ProtoCommandError < Net::ProtocolError
end
class Net::ProtoRetriableError < Net::ProtocolError
end
class Net::OpenTimeout < Timeout::Error
end
class Net::ReadTimeout < Timeout::Error
end
class Net::WriteTimeout < Timeout::Error
end
class Net::BufferedIO
end
class Net::InternetMessageIO < Net::BufferedIO
end
class Net::WriteAdapter
end
class Net::ReadAdapter
end
module Net::NetPrivate
end
