# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: ignore
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/nokogiri-1.13.6-x86_64/all/nokogiri-1.13.6-x86_64.rbi
#
# nokogiri-1.13.6-x86_64-darwin

module Nokogiri
end
class Nokogiri::VersionInfo
  extend Singleton::SingletonClassMethods
  include Singleton
end
module Nokogiri::ClassResolver
end
class Nokogiri::SyntaxError < StandardError
end
module Nokogiri::XML
end
module Nokogiri::XML::PP
end
module Nokogiri::XML::PP::Node
end
module Nokogiri::XML::PP::CharacterData
end
class Nokogiri::XML::ParseOptions
end
module Nokogiri::XML::SAX
end
class Nokogiri::XML::SAX::Document
end
class Nokogiri::XML::SAX::ParserContext
end
class Nokogiri::XML::SAX::Parser
end
class Nokogiri::XML::SAX::Parser::Attribute < Anonymous_Struct_23
end
class Nokogiri::XML::SAX::PushParser
end
module Nokogiri::XML::Searchable
end
class Nokogiri::XML::Node
  include Enumerable
  include Nokogiri::ClassResolver
  include Nokogiri::XML::PP::Node
  include Nokogiri::XML::Searchable
end
class Nokogiri::XML::Node::SaveOptions
end
class Nokogiri::XML::AttributeDecl < Nokogiri::XML::Node
end
class Nokogiri::XML::ElementDecl < Nokogiri::XML::Node
end
class Nokogiri::XML::ElementContent
end
class Nokogiri::XML::CharacterData < Nokogiri::XML::Node
  include Nokogiri::XML::PP::CharacterData
end
class Nokogiri::XML::Namespace
  include Nokogiri::XML::PP::Node
end
class Nokogiri::XML::Attr < Nokogiri::XML::Node
end
class Nokogiri::XML::DTD < Nokogiri::XML::Node
end
class Nokogiri::XML::CDATA < Nokogiri::XML::Text
end
class Nokogiri::XML::Text < Nokogiri::XML::CharacterData
end
class Nokogiri::XML::Document < Nokogiri::XML::Node
end
class Nokogiri::XML::DocumentFragment < Nokogiri::XML::Node
end
class Nokogiri::XML::ProcessingInstruction < Nokogiri::XML::Node
end
class Nokogiri::XML::NodeSet
  include Enumerable
  include Nokogiri::XML::Searchable
end
class Nokogiri::XML::SyntaxError < Nokogiri::SyntaxError
end
module Nokogiri::XML::XPath
end
class Nokogiri::XML::XPath::SyntaxError < Nokogiri::XML::SyntaxError
end
class Nokogiri::XML::XPathContext
end
class Nokogiri::XML::Builder
  include Nokogiri::ClassResolver
end
class Nokogiri::XML::Builder::NodeBuilder
end
class Nokogiri::XML::Reader
  include Enumerable
end
class Nokogiri::XML::Notation < Anonymous_Struct_24
end
class Nokogiri::XML::EntityDecl < Nokogiri::XML::Node
end
class Nokogiri::XML::EntityReference < Nokogiri::XML::Node
end
class Nokogiri::XML::Schema
end
class Nokogiri::XML::RelaxNG < Nokogiri::XML::Schema
end
module Nokogiri::XSLT
end
class Nokogiri::XSLT::Stylesheet
end
module Nokogiri::HTML4
end
class Nokogiri::HTML4::EntityDescription < Anonymous_Struct_25
end
class Nokogiri::HTML4::EntityLookup
end
class Nokogiri::HTML4::Document < Nokogiri::XML::Document
end
class Nokogiri::HTML4::Document::EncodingFound < StandardError
end
class Nokogiri::HTML4::Document::EncodingReader
end
class Nokogiri::HTML4::Document::EncodingReader::SAXHandler < Nokogiri::XML::SAX::Document
end
class Nokogiri::HTML4::Document::EncodingReader::JumpSAXHandler < Nokogiri::HTML4::Document::EncodingReader::SAXHandler
end
class Nokogiri::HTML4::DocumentFragment < Nokogiri::XML::DocumentFragment
end
module Nokogiri::HTML4::SAX
end
class Nokogiri::HTML4::SAX::ParserContext < Nokogiri::XML::SAX::ParserContext
end
class Nokogiri::HTML4::SAX::Parser < Nokogiri::XML::SAX::Parser
end
class Nokogiri::HTML4::SAX::PushParser < Nokogiri::XML::SAX::PushParser
end
class Nokogiri::HTML4::ElementDescription
end
class Nokogiri::HTML4::Builder < Nokogiri::XML::Builder
end
module Nokogiri::Decorators
end
module Nokogiri::Decorators::Slop
end
module Nokogiri::CSS
end
class Nokogiri::CSS::Node
end
class Nokogiri::CSS::XPathVisitor
end
module Nokogiri::CSS::XPathVisitor::BuiltinsConfig
end
module Nokogiri::CSS::XPathVisitor::DoctypeConfig
end
module Nokogiri::CSS::XPathVisitorAlwaysUseBuiltins
end
module Nokogiri::CSS::XPathVisitorOptimallyUseBuiltins
end
class Nokogiri::CSS::Parser < Racc::Parser
end
class Nokogiri::CSS::Tokenizer
end
class Nokogiri::CSS::Tokenizer::ScanError < StandardError
end
class Nokogiri::CSS::SyntaxError < Nokogiri::SyntaxError
end
module Nokogiri::HTML5
end
class Nokogiri::HTML5::Document < Nokogiri::HTML4::Document
end
class Nokogiri::HTML5::DocumentFragment < Nokogiri::HTML4::DocumentFragment
end
module Nokogiri::HTML5::Node
end
module Nokogiri::Gumbo
end
