/* tslint:disable */
/* eslint-disable */
/**
 * test-open-api
 * ほげほげ説明
 *
 * The version of the OpenAPI document: 1.0
 * Contact: test@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Blog
 */
export interface Blog {
    /**
     * 
     * @type {number}
     * @memberof Blog
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Blog
     */
    contents?: string;
    /**
     * 
     * @type {Date}
     * @memberof Blog
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Blog
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the Blog interface.
 */
export function instanceOfBlog(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlogFromJSON(json: any): Blog {
    return BlogFromJSONTyped(json, false);
}

export function BlogFromJSONTyped(json: any, ignoreDiscriminator: boolean): Blog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'contents': !exists(json, 'contents') ? undefined : json['contents'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function BlogToJSON(value?: Blog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'contents': value.contents,
    };
}

