/* tslint:disable */
/* eslint-disable */
/**
 * test-open-api
 * ほげほげ説明
 *
 * The version of the OpenAPI document: 1.0
 * Contact: test@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignOut200Response
 */
export interface SignOut200Response {
    /**
     * 成功判定
     * @type {boolean}
     * @memberof SignOut200Response
     */
    readonly success: boolean;
}

/**
 * Check if a given object implements the SignOut200Response interface.
 */
export function instanceOfSignOut200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function SignOut200ResponseFromJSON(json: any): SignOut200Response {
    return SignOut200ResponseFromJSONTyped(json, false);
}

export function SignOut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignOut200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function SignOut200ResponseToJSON(value?: SignOut200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

