/* tslint:disable */
/* eslint-disable */
/**
 * test-open-api
 * ほげほげ説明
 *
 * The version of the OpenAPI document: 1.0
 * Contact: test@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface SignUp200Response
 */
export interface SignUp200Response {
    /**
     * 
     * @type {User}
     * @memberof SignUp200Response
     */
    data: User;
}

/**
 * Check if a given object implements the SignUp200Response interface.
 */
export function instanceOfSignUp200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function SignUp200ResponseFromJSON(json: any): SignUp200Response {
    return SignUp200ResponseFromJSONTyped(json, false);
}

export function SignUp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUp200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': UserFromJSON(json['data']),
    };
}

export function SignUp200ResponseToJSON(value?: SignUp200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': UserToJSON(value.data),
    };
}

